/* autogenerated but no overwrite, you can modify it */

#define PY_SSIZE_T_CLEAN
#include <Python.h>
#include <gcc-plugin.h>
#include "tree.h"
#include "print-tree.h"
#include "pyplugcc-mgcc-tree.h"

/*
extern void debug_tree (tree);
*/

PyObject *Py_debug_tree(PyObject *self, PyObject *args) {
  PyObject *tree_0;
  if (!PyArg_ParseTuple (args,"O:debug_tree", &tree_0)) return NULL;
  debug_tree((tree)Get_gccdata(tree_0));
  Py_RETURN_NONE;
}

/*
extern void debug_raw (const tree_node *ptr);
*/

PyObject *Py_debug_raw(PyObject *self, PyObject *args) {
  PyObject *ptr_0;
  if (!PyArg_ParseTuple (args,"O:debug_raw", &ptr_0)) return NULL;
  debug_raw((tree_node*)Get_gccdata(ptr_0));
  Py_RETURN_NONE;
}

/*
extern void debug (const tree_node *ptr);
*/

PyObject *Py_debug(PyObject *self, PyObject *args) {
  PyObject *ptr_0;
  if (!PyArg_ParseTuple (args,"O:debug", &ptr_0)) return NULL;
  debug((tree_node*)Get_gccdata(ptr_0));
  Py_RETURN_NONE;
}

/*
extern void debug_head (const tree_node *ptr);
*/

PyObject *Py_debug_head(PyObject *self, PyObject *args) {
  PyObject *ptr_0;
  if (!PyArg_ParseTuple (args,"O:debug_head", &ptr_0)) return NULL;
  debug_head((tree_node*)Get_gccdata(ptr_0));
  Py_RETURN_NONE;
}

/*
extern void debug_body (const tree_node *ptr);
*/

PyObject *Py_debug_body(PyObject *self, PyObject *args) {
  PyObject *ptr_0;
  if (!PyArg_ParseTuple (args,"O:debug_body", &ptr_0)) return NULL;
  debug_body((tree_node*)Get_gccdata(ptr_0));
  Py_RETURN_NONE;
}

/*
extern void print_decl_identifier (FILE *, tree, int flags);
*/

PyObject *Py_print_decl_identifier(PyObject *self, PyObject *args) {
  FILE * file_0;
  PyObject *tree_1;
  int flags_2;
  if (!PyArg_ParseTuple (args,"OOO:print_decl_identifier", &file_0, &tree_1,
    &flags_2)) return NULL;
  print_decl_identifier(file_0, (tree)Get_gccdata(tree_1), flags_2);
  Py_RETURN_NONE;
}


/*
return a full string ouput of the tree (tree, const char prefix = '', int indent = 0, bool brief_for_visited = true)
*/
PyObject *Py_node_as_string(PyObject *self, PyObject *args) {
  FILE * file_0;
  char * char_1 = (char*)"";
  PyObject *tree_2;
  int int_3 = 0;
  bool brief_for_visited_4 = true;
  char *ptr;
  size_t size;
  file_0 = open_memstream(&ptr, &size);
  if (file_0 == NULL) return  PyErr_SetFromErrno(PyExc_RuntimeError);
  if (!PyArg_ParseTuple (args,"O|sii:print_node", &tree_2, &char_1,
    &int_3, &brief_for_visited_4)) return NULL;
  print_node(file_0, char_1, (tree)Get_gccdata(tree_2), int_3,
         brief_for_visited_4);
  fclose(file_0);
  PyObject *result = Py_BuildValue("s#", ptr, size);
  free(ptr);
  return result;
}

/*
return a brief string ouput of the tree (tree, const char prefix = '', int indent = 0, bool brief_for_visited = true)
*/
PyObject *Py_node_brief_as_string(PyObject *self, PyObject *args) {
  FILE * file_0;
  char * char_1 = (char *)"";
  PyObject *tree_2;
  int int_3 = 0;
  char *ptr;
  size_t size;
  file_0 = open_memstream(&ptr, &size);
  if (file_0 == NULL) return  PyErr_SetFromErrno(PyExc_RuntimeError);
  if (!PyArg_ParseTuple (args,"O|si:print_node", &tree_2, &char_1,
    &int_3)) return NULL;
  print_node_brief(file_0, char_1, (tree)Get_gccdata(tree_2), int_3);
  fclose(file_0);
  PyObject *result = Py_BuildValue("s#", ptr, size);
  free(ptr);
  return result;
}
